파이썬에서는 하나의 변수에 여러 데이터를 넣는 방법으로 '리스트'를 사용한다. 하지만 리스트는 메모리를 많이 차지하고 속도가 느린 단점이 있다. 이러한 단점을 보완하기 위해선 배열(Array)를 사용하는 것이 좋다. 파이썬에서는 'NumPy'라는 패키지를 사용하여 배열을 사용할 수 있다. 'NumPy'에서 제공하는 배열과 파이썬에서 기본으로 제공하는 리스트에는 두 가지 차이가 있다.

1. 리스트에는 element의 type이 달라도 되지만 배열에서는 동일해야 한다.
2. 배열에서는 element 개수를 변경할 수 없다.

'NumPy'에서 구현된 반복문은 C로 구현되어 있어 속도가 빠르고 vectorized operation을 제공해 간단한 코드로 선형대수 연산을 수행할 수 있다.
또한, 배열 인덱싱을 사용한 질의 기능을 이용해 간단한 코드로 복잡한 연산을 수행할 수 있다.

## NumPy 패키지 임포트
관례적으로 'numpy' 패키지는 'np'라고 aliasing을 붙인다.

In [1]:
import numpy as np

## 배열 생성 1
배열을 생성하기 위한 가장 쉬운 방법으로는 아래와 같이 리스트 객체를 사용하여 N차원의 배열을 만들수 있다.


In [2]:
dim_1_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
dim_1_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
dim_2_array = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
dim_2_array

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [4]:
dim_3_array = arr3dim = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]
])
dim_3_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

## 배열 생성 2
리스트를 이용해 배열을 생성하는 방법 이외에서 zeros, ones, arange 등을 사용해 배열을 생성할 수 있다.

또한, 선형 구간 혹튼 로그 구간을 지정한 구간의 수만큼 분할된 배열을 생성하거나 임의의 난수가 분포된 랜덤 배열을 생성할 수도 있다.

In [5]:
zeros_array = np.zeros(shape=(2, 2), dtype=np.int32)
zeros_array

array([[0, 0],
       [0, 0]], dtype=int32)

In [6]:
ones_array = np.ones(shape=(2, 2), dtype=np.float16)
ones_array

array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float16)

In [7]:
arange_array = np.arange(10)
arange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
linspace_array = np.linspace(0, 100, 5)
linspace_array

array([   0.,   25.,   50.,   75.,  100.])

In [9]:
logspace = np.logspace(0, 4, 4)
logspace

array([  1.00000000e+00,   2.15443469e+01,   4.64158883e+02,
         1.00000000e+04])

In [10]:
np.random.seed(0)
print(np.random.rand(4))
print(np.random.rand(3, 5))

[ 0.5488135   0.71518937  0.60276338  0.54488318]
[[ 0.4236548   0.64589411  0.43758721  0.891773    0.96366276]
 [ 0.38344152  0.79172504  0.52889492  0.56804456  0.92559664]
 [ 0.07103606  0.0871293   0.0202184   0.83261985  0.77815675]]


## 배열의 차원과 모양
ndim과 shape 속성을 이용해 배열의 차원과 모양을 알 수 있다.

In [11]:
print("배열의 차원을 출력합니다.")
print(dim_1_array.ndim)
print(dim_2_array.ndim)
print(dim_3_array.ndim)

배열의 차원을 출력합니다.
1
2
3


In [12]:
print("배열의 모양을 출력합니다.")
print(dim_1_array.shape)
print(dim_2_array.shape)
print(dim_3_array.shape)

배열의 모양을 출력합니다.
(10,)
(2, 4)
(2, 3, 4)


## 배열 인덱싱&슬라이싱
배열에서도 리스트와 마찬가지로 인덱싱과 슬라이싱 기능을 사용할 수 있습니다.

In [13]:
print(dim_1_array[0])
print(dim_1_array[-1])
print(dim_1_array[:6])

0
9
[0 1 2 3 4 5]


In [14]:
print(dim_2_array[0][0])
print(dim_2_array[-1][-1])
print(dim_2_array[:1, :3])

10
80
[[10 20 30]]


In [15]:
print(dim_3_array[0][0][0])
print(dim_3_array[-1][-1][-1])
print(dim_3_array[:1, :2, :3])

1
22
[[[1 2 3]
  [5 6 7]]]


## Fancy Indexing
'Fancy Indexing'은 배열 인덱싱 방법 중 하나로 질의문을 통해 인덱싱을 수행할 수 있는 기능이다.

In [16]:
print(dim_1_array[dim_1_array % 2 == 0])

[0 2 4 6 8]
