## NumPy 연산

In [1]:
import numpy as np

### Vectorized operation
'NumPy'는 코드의 간결성과 계산 속도를 높이기 위해 'vectorized operation'을 지원한다. 반복문을 사용하지 않고 선형대수의 벡터 혹은 행렬 연산을 수행할 수 있다. 아래와 같이 반복문을 이용한 계산과 'NumPy'에서 제공하는 vectorized operation 속도를 비교해 볼 수 있다.

In [2]:
x = np.arange(1, 1001)
y = np.arange(1001, 2001)

In [3]:
%%time
z = np.zeros_like(x)
for i in range(1000):
    z[i] = x[i] + y[i]

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 818 µs


In [4]:
%%time
z = x+y

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 149 µs


### 비교, 지수함수, 로그함수 등에도 vectorized operation을 사용할 수 있다.
- np.all
- np.exp
- np.log
- np.log10

In [5]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([4, 2, 2, 4])

print(array1 == array2)
print(array1 >= array2)

[False  True False  True]
[False  True  True  True]


#### np.all

In [6]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([4, 2, 2, 4])
array3 = np.array([1, 2, 3, 4])

print(np.all(array1 == array2))
print(np.all(array1 == array3))

False
True


#### np.exp & np.log & np.log10

In [7]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [8]:
print(np.exp(array))
print(np.log(array))
print(np.log10(array))

[  1.           2.71828183   7.3890561   20.08553692  54.59815003]
[       -inf  0.          0.69314718  1.09861229  1.38629436]
[       -inf  0.          0.30103     0.47712125  0.60205999]


/home/bhappy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/home/bhappy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log10
  This is separate from the ipykernel package so we can avoid doing imports until


### 차원 축소 연산
행렬의 row 또는 col을 하나의 데이터 집합으로 보고 평균, 최대/최소 등의 연산을 거쳐 하나의 값으로 나오게한다. 이러한 연산을 'Dimension Reduction' 이라고 한다.

- 최대/최소 : min, max, argmin, argmax
- 통계 : sum, mean, median, std, var
- 불리언 : all, any

In [9]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
print(np.min(array))
print(np.max(array))

# 인덱스를 리턴
print(np.argmin(array))
print(np.argmax(array))

1
10
0
9


In [11]:
print(np.sum(array))
print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.var(array))

55
5.5
5.5
2.87228132327
8.25


#### 2차원 이상의 배열일 경우 계산할 축을 지정한다.

In [12]:
array2dim = np.arange(10).reshape(2, 5)
array2dim

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
print(np.sum(array2dim, axis=1))
print(np.sum(array2dim, axis=0))

[10 35]
[ 5  7  9 11 13]


### 정렬
리스트에서 쓰이는 sort와 같이 NumPy 배열에서도 np.sort를 사용해 배열 안의 element를 정렬할 수 있다. 2차원 이상일 경우 마찬가지로 축을 지정한다. 또한, 객체.sort() 메소드는 객체의 자료 자체가 변경되는 in-place 메소드이므로 원본이 훼손되지 않게 주의를 해야한다.

In [14]:
array = np.array([[4, 3, 5], [1, 2, 1]])
array

array([[4, 3, 5],
       [1, 2, 1]])

In [15]:
np.sort(array)

array([[3, 4, 5],
       [1, 1, 2]])

In [16]:
array

array([[4, 3, 5],
       [1, 2, 1]])

In [17]:
array.sort(axis=0)
array

array([[1, 2, 1],
       [4, 3, 5]])